<?php
/**
 * Created by PhpStorm.
 * User : Leopard
 * Date : 2018/2/2
 * Time : 13:43
 * Email: 417780879@qq.com
 */
namespace app\admin\controller;
use app\common\controller\Common;
use think\Request;

class Messages extends Common
{
    public function _initialize()
    {
        parent ::_initialize(); // TODO: Change the autogenerated stub
        $this->model=new \app\index\model\Messages();
        $this->url=url('admin/messages/index');
    }

    public function index(){
        $messData=$this->model->order('id desc')->select();
        $this->assign('messData',$messData);
        return view();
    }

    public function delmessages(Request $request){
        if($request->isGet()){
            $id=$request->param('id');
            $num=$this->model->destroy($id);
            $this->return_del($num,$this->url);
        }
    }
}