<?php
namespace app\index\controller;

class Abouts extends Actives
{
    public function _initialize()
    {
        parent ::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index(){
        $dongData=\app\admin\model\News::where('cid',2)->field('nid,title')->limit(4)->select();
        $this->assign('dongData',$dongData);
        return view();
    }
}
