<?php
/**
 * Created by PhpStorm.
 * User : Leopard
 * Date : 2018/3/22
 * Time : 10:34
 * Email: 417780879@qq.com
 */
namespace app\index\controller;
use app\admin\model\Banner;
use think\Controller;

class Base extends Controller
{
    public $active=1;
    public function _initialize()
    {
        parent ::_initialize(); // TODO: Change the autogenerated stub
        $bannerData=Banner::order('sort desc')->limit(3)->select();
        $this->assign('bannerData',$bannerData);
    }
}