<?php
/**
 * Created by PhpStorm.
 * User : Leopard
 * Date : 2018/3/27
 * Time : 16:16
 * Email: 417780879@qq.com
 */
namespace app\index\controller;
use think\Request;

class Union extends Actives
{
    public function _initialize()
    {
        parent ::_initialize(); // TODO: Change the autogenerated stub
        $this->model=new \app\admin\model\News();
    }

    public function index(){
        $list=$this->model->where('cid',6)->paginate(4);
        $page = $list->render();
        // 模板变量赋值
        $this->assign('list', $list);
        $this->assign('page', $page);
        return view();
    }
    public function content(Request $request)
    {
        $nid=$request->param('nid/d');
        $data=$this->model->get($nid);
        $up=$this->model->where('cid',$data['cid'])->where('nid','<',$nid)->order('nid desc')->limit(1)->select()->toArray();
        $down=$this->model->where('cid',$data['cid'])->where('nid','>',$nid)->order('nid')->limit(1)->select()->toArray();
        $up=$up?$up[0]['nid']:0;
        $down=$down?$down[0]['nid']:0;
        $this->assign('up',$up);
        $this->assign('down',$down);
        $this->assign('data',$data);
        return view();
    }
}